//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "baseline")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", indexed)]
    pub uuid: String,
    #[sea_orm(column_type = "Blob")]
    pub pcr_digest: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub ba: String,
    #[sea_orm(column_name = "ima-log", column_type = "Text")]
    pub ima_log: String,
    #[sea_orm(column_name = "tpm-log", column_type = "Blob")]
    pub tpm_log: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub nonce: String,
    #[sea_orm(column_type = "Timestamp")]
    pub established_at: DateTime<Utc>,
    #[sea_orm(column_type = "Boolean", indexed)]
    pub is_accepted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clients::Entity",
        from = "Column::Uuid",
        to = "super::clients::Column::Uuid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Clients,
    #[sea_orm(has_many = "super::push_session::Entity")]
    PushSession,
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::push_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PushSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
