name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    steps:
      - uses: actions/checkout@v4
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: |
          sudo apt-get install -y libtss2-dev
          cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paranoid-system
          path: |
            target/release/paranoid-boot
            target/release/paranoid-rt
            target/release/paranoid-srv
    
